//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int BuyID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ExpectPrice { get; set; }
        public string TradeOrBuy { get; set; }
        public Nullable<int> UID { get; set; }
    
        public virtual User User { get; set; }
    }
}
